name: GitHub CentroAMAI deploy

on:
  # Activa el workflow cada vez que hay un push a la rama `main`
  # ¿Estás usando un nombre diferente de rama? Reemplaza `main` con el nombre de tu rama
  push:
    branches: [deploy]
  # Te permite ejecutar este workflow manualmente desde la pestaña Actions en GitHub.
  workflow_dispatch:

# Permite clonar el repositorio y desplegar el proyecto
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Deploy to FTP server
        uses: radenpioneer/astro-ftp-deploy@v0.1.1
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          node-version: 20
          package-manager: npm@latest
          directory: ./
