name: GitHub CentroAMAI deploy

on:
  # Activa el workflow cada vez que hay un push a la rama `main`
  # ¿Estás usando un nombre diferente de rama? Reemplaza `main` con el nombre de tu rama
  push:
    branches: [deploy]
  # Te permite ejecutar este workflow manualmente desde la pestaña Actions en GitHub.
  workflow_dispatch:

# Permite clonar el repositorio y desplegar el proyecto
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          node-version: 20 # La versión específica de Node que debe utilizarse para compilar tu proyecto. Por defecto es la 18. (opcional)
          package-manager: npm@20.14.0 # El gestor de paquetes de Node que debe instalar las dependencias y compilar tu proyecto. Automáticamente detectadas con base en tu archivo lockfile. (opcional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Deploy to FTP server
        uses: radenpioneer/astro-ftp-deploy@v0.1.1
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          node-version: 20
